Output demo/themes.gif

Set FontSize 14
Set Width 1300
Set Height 600
Set Padding 20

Set Theme "Catppuccin Latte"

# Nord theme
Type "./chooz --theme nord testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Escape
Sleep 600ms

# Dracula theme
Type "./chooz --theme one-light testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Escape
Sleep 600ms

Set Theme "Nord"
# Nord theme
Type "./chooz --theme nord testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Escape
Sleep 600ms

# Dracula theme
Type "./chooz --theme one-light testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Escape
Sleep 600ms

Set Theme "Nord"
# Theme showroom
Type "./chooz theme-showroom"
Enter
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right


Set Theme "Catppuccin Latte"
# Theme showroom
Type "./chooz theme-showroom"
Enter
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right

Type "q"
Sleep 1600ms
