Output demo/themes_light.gif

Set FontSize 14
Set Width 1300
Set Height 600
Set Theme "Catppuccin Latte"
Set Padding 20

Type "./chooz --theme dracula testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Escape
Sleep 600ms

Type "./chooz --theme catppuccin-latte testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Escape
Sleep 600ms

Type "./chooz --theme kanagawa testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Escape
Sleep 600ms

Type "./chooz theme-showroom"
Enter
Sleep 1s
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Right
Sleep 800ms
Type "q"
Sleep 800ms
