Output demo/themes.gif

Set FontSize 14
Set Width 1300
Set Height 600
Set Theme "Catppuccin Mocha"
Set Padding 20

# Nord theme
Type "./chooz --theme nord testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Escape
Sleep 600ms

# Dracula theme
Type "./chooz --theme dracula testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Escape
Sleep 600ms

# Theme showroom
Type "./chooz --theme-showroom testdata/big.yaml"
Enter
Sleep 1s
Down
Sleep 700ms
Down
Sleep 700ms
Down
Sleep 700ms
Down
Sleep 700ms
Down
Sleep 700ms
Down
Sleep 700ms
Type "q"
Sleep 600ms
